config/routes.rb
Rails.application.routes.draw do
  resources :screenings
  resources :theaters
  resources :cinemas
  devise_for :users, :path => '', :path_names => {:sign_in =>'login', :sign_out =>'logout'}
  resources :users

  resources :products
  get 'static_pages/booking'

  get 'static_pages/book'

  get 'static_pages/cinemas'

  get 'static_pages/movies'

  get 'static_pages/promoevents'

  get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/index'

  get 'static_pages/thank_you'

  get 'products/index'

  get 'products/new'

  get 'products/create'

  post 'products/create'

  get 'products/show'

  resources :orders

  get 'orders/index'

  get 'orders/new'

  get 'orders/create'

   get 'orders/show'

  post 'static_pages/thank_you'

  get 'static_pages/update_cinemas', as 'update_cinemas'

   root 'static_pages#cinemas'

   resources :products, :orders, only: [:index, :show, :new, :create]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
   	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<!-- ***********CSS************** -->

<!-- ********fonts********* -->

<link href='http://fonts.googleapis.com/css?family=Roboto:400,100italic,300italic,500,700' rel='stylesheet' type='text/css'>

<!-- ******bootstrap**** -->

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
<link href="css/normalize.css" rel="stylesheet">
<link href="https://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css" rel ="stylesheet">
<link href="https://code.jquery.com/ui/1.9.0/themes/smoothness/jquery-ui.css" rel ="stylesheet">

  <title>Modern Manila Movies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="menu-header">
		<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header page-scroll">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
						<span class="sr only"> </span>
              			<span class="icon-bar"></span>
              			<span class="icon-bar"></span>
              			<span class="icon-bar"></span>
					</button>
					<%= link_to "Moderne Manila Movies", static_pages_index_path %><!-- site name -->
					
				</div> <!-- end of navbar page-scroll -->

				<div class="collapse navbar-collapse navbar-right navbar-main-collapse">
					<!-- Menu -->
					<ul class="nav navbar-nav">
						<li><%= link_to "Movies", static_pages_movies_path %></li>
						<li><%= link_to "Cinemas", static_pages_cinemas_path %></li>
						<li><%= link_to "Promo/Events", static_pages_promoevents_path %></li>
						<li><%= link_to "Contact", static_pages_contact_path %></li>
						<% if user_signed_in? %>
						<li>
							<%= link_to('Logout', destroy_user_session_path) %>
						</li>
						<% else %>
						<li>
							<%= link_to('Login', new_user_session_path) %>
						</li>
						<% end %>
						<% if user_signed_in? %>
  						<li>
  						<%= link_to('Edit Profile', edit_user_registration_path) %>
  						</li>
						<% else %>
  						<li>
  						<%= link_to('Register', new_user_registration_path)  %>
  						</li>
						<% end %>
						<li class = "searchbox">
							<%= form_tag("/products", method: "get") do %>
							  <%= label_tag(:q, 'Search for:') %>
							  <searchtext><%= text_field_tag(:q) %></searchtext>
							  <searchbutton><%= submit_tag("Search") %></searchbutton>
							<% end %>
						</li>
						
					</ul><!-- End Menu -->
				</div> <!-- end of collapse navbar-collapse -->
			</div> <!-- end of container -->
		</nav> <!-- end of navbar -->
	</div>  <!-- end of menu-header -->
       	
	<div class="header">
		<h1>Welcome to Moderne Manila Movies</h1>
		<h3 class = "timestamp">Welcome! The date and time is <%= Time.now %></h3>
		<h2>Your one stop movie reservation guide in Manila</h2>
	
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

		<div class = "filters">
			<%= form_for :order, url: {action: "show"}, html: {method: "get"} do |f| %>
			<div class = "col-md-2">
				<div class = "select-style">
					<select id = "pelikula">
						<%= f.select :product_id, options_for_select(@product.collect {|product| [product.name.titleize, product.id] }, 1), {}, {id: 'product_select'} %>
					</select>
				</div> <!-- end of select-style -->
			</div> <!-- end of col -->
			<div class = "col-md-2">
				<div class = "select-style">
					<select id = "sinehan">
						<%= f.select :cinema_id, options_for_select(@cinema.collect {|cinema| [cinema.name.titleize, cinema.id] }, 1), {}, {id: 'cinema_select'} %>
					</select>
				</div> <!-- end of select-style -->
			</div> <!-- end of col -->
			<div class = "col-md-2">
				<div class = "select-style">
					<select id = "kelan">
						<%= f.select :screening_id, options_for_select(@screening.collect {|screening| [screening.name.titleize, screening.id] }, 1), {}, {id: 'screening_select'} %>
					</select>
				</div> <!-- end of select-style -->
			</div> <!-- end of col -->
			<div class = "col-md-2">
				<div class = "select-style">
					<select id = "teatro">
						<%= f.select :cinema_id, options_for_select(@cinema.collect {|cinema| [cinema.name.titleize, cinema.id] }, 1), {}, {id: 'cinema_select'} %>
					</select>
				</div> <!-- end of select-style -->
			</div> <!-- end of col -->
			<div class = "col-md-3">
					<button type="bookbutton" class="btn btn-warning"><%= f.submit "Book Now" %></button>
				</div> <!-- end of select-style -->
			</div> <!-- end of col -->
		</div> <!-- end of filters -->
		<% end %>
		<div class = "row">
			<div class = "col-md-8 col-xs-12">
				
			</div> <!-- end of column -->
	</div> <!-- end of header -->	

<%= yield %>

</body>

<footer>
  <div class = "footer">
    <div class="fb-share" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like" data-show-faces="true" data-share="true">
      <div class="fb-follow" data-href="https://www.facebook.com/zuck" data-colorscheme="light" data-layout="standard" data-show-faces="true"></div>
    </div>
    <div class = "twittershare">
      <a href="https://twitter.com/wahnderlush" class="twitter-follow-button" data-show-count="false">Follow @wahnderlush</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    </div>
    <br>
    &copy;Ahn Bustamante 2015
  </div>
</footer> 
<!-- **********Scripts************ -->

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>

</html>